---
- file: path=/etc/sudoers.d state=directory mode=0755
  become: true
- name: sudo access for vagrant-hostmanager
  copy: src=vagrant_hostmanager dest=/etc/sudoers.d/vagrant_hostmanager
  become: true

- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - gpg
    - gpg-agent
    - vim
    - cask
    - wget
    - pwgen
    - tree
    - mtr
    - ncftp
    - pandoc
    - lynx
    - mosh
    - ssh-copy-id
# brew install lastpass-cli --with-pinentr

- name: Install ancillary applications
  homebrew_cask: name={{ item }} state=present
  with_items:
      # Downloads from the Oracle download site
      - java
      - firefox
      - google-chrome
      - google-hangouts
      - virtualbox
      - vagrant
      - quicksilver
      - evernote
      - skitch
#      - hipchat
      - iterm2
#      - dropbox
      - tunnelblick
#      - lastpass
#      - xmarks-safari
      - fluid
      - divvy
      - rescuetime
#      - chefdk036
      - mou
      - choosy
      - cleanmymac
      - macvim
#      - totalfinder
      - cyberduck

- name: clone dotfiles (make sure ~/.ssh is valid!)
  git: repo=ssh://git@github.com/simonmcc/dot-files.git dest={{ home }}/dot-files update=no
  when: false

- name: link to everything in ~/dot-files
  command: ./setup.sh
  args:
    chdir: /Users/mccartsi/dot-files
    creates: /Users/mccartsi/.vimrc
  when: false

- include: python.yml
