---
- file: path=/etc/sudoers.d state=directory mode=0755
  become: true

- name: sudo access for vagrant-hostmanager
  template: src=vagrant_hostmanager dest=/etc/sudoers.d/vagrant_hostmanager
  become: true

- name: Install required software (Homebrew)
  homebrew: name={{ item }} state=present
  with_items:
    - awscli
    - dos2unix
    - jq
    - terraform
    - terraforming
    - shellcheck
    - git-crypt
    - vim
    - cask
    - wget
    - pwgen
    - tree
    - mtr
    - ncftp
    - ssh-copy-id
    - mas

- name: Install required software (Homebrew casks)
  homebrew_cask: name={{ item }} state=present
  with_items:
      - 1password
      - alfred
      - blue-jeans
      - docker
      - gpg-suite
      - iterm2
      - macdown
      - macvim
      - virtualbox
# virtualbox-extension-pack needs the sudo password
# brew cask install virtualbox-extension-pack
      - vagrant

# - include: python.yml
