---
- file: path=/etc/sudoers.d state=directory mode=0755
  become: true

- name: sudo access for vagrant-hostmanager
  template: src=vagrant_hostmanager dest=/etc/sudoers.d/vagrant_hostmanager
  become: true

- name: Install required software (Homebrew)
  homebrew: name={{ item }} state=present
  with_items:
    - vim
    - cask
    - wget
    - pwgen
    - tree
    - mtr
    - ncftp
    - ssh-copy-id
    - mas

- name: Install required software (Homebrew casks)
  homebrew_cask: name={{ item }} state=present
  with_items:
      - virtualbox
# virtualbox-extension-pack needs the sudo password
# brew cask install virtualbox-extension-pack
      - vagrant
      - alfred
#      - skitch
      - iterm2
#      - dropbox
#      - tunnelblick
      - macdown
      - macvim
#      - cyberduck
      - 1password
      - gpg-suite

# - include: python.yml
