---
- name: easy install pip
  easy_install: name=pip
  sudo: yes

- name: install apps from pip
  pip: name={{item}}
  sudo: yes
  with_items:
      - virtualenv
      - cliff
      - pyyaml
      - awscli
      - python-novaclient
      - git-review
