---
- name: easy install pip
  easy_install: name=pip
  become: yes

- name: install apps from pip
  pip: name={{item}}
  become: yes
  with_items:
      - virtualenv
      - cliff
      - pyyaml
      - awscli
#      - python-novaclient
#      - git-review
